events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # this code attributed to Nat Tuck's router lecture code, as they are similar

  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    get "/users/:id/photo", UserController, :photo
    resources "/comments", CommentController
    resources "/responses", ResponseController

    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end




  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

events/lib/events_web/templates/page/index.html.eex
<div class="row">
  <div class="column">
    <h1> Event Feed </h1>
  </div>
</div>


<%= if have_current_user?(@conn) do %>
  <span><%= link "New Post", to: Routes.post_path(@conn, :new) %></span>
<% end %>


<div class="row">
  <%= for post <- @posts do %>
    <div class="col-sm-4 card text-center">

      <div class="card-body">
        <h5 class="card-title"> <%= post.name %></h5>

        <p class="card-text"><u><%= post.date %></u></p>
        <p class="card-text"> <%= post.body %></p>
        <%= link("view", to: Routes.post_path(@conn, :show, post)) %>

      </div>
      <div class="card-footer">
        Posted by <%= post.user.name %>
        <% src = Routes.user_path(@conn, :photo, post.user) %>
        <img src="<%= src %>" alt="" width="50" height="50">
      </div>
    </div>
  <% end %>
</div>